import { Platform, StyleSheet } from 'react-native';
import { hp, wp } from '../helpers/common';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(6),
    paddingTop: Platform.select({ ios: hp(1.5), android: hp(4) }),
    paddingBottom: hp(2.5),
  },
  avatarContainer: { width: wp(9), height: wp(9), borderRadius: wp(5), overflow: 'hidden', borderWidth: 1, borderColor: '#ddd' },
  avatar: { width: '100%', height: '100%' },
  avatarPlaceholder: { width: '100%', height: '100%', backgroundColor: 'transparent' },
  content: { flex: 1, paddingHorizontal: wp(6), paddingTop: hp(2) },
  greeting: { fontSize: hp(3), fontWeight: '600', color: '#007AFF', marginBottom: hp(3) },
  sectionTitle: { fontSize: hp(2.4), fontWeight: '600', color: '#333', marginTop: hp(3), marginBottom: hp(2) },
  section: { marginBottom: hp(3) },
  label: { fontSize: hp(2), fontWeight: '600', color: '#333', marginBottom: hp(1) },
  question: { fontSize: hp(2), fontWeight: '600', color: '#000', marginBottom: hp(1.5) },
  row: { flexDirection: 'row', gap: wp(4), alignItems: 'center' },
  radioGroup: { gap: hp(1.2) },
  radio: { flex: 1, flexDirection: 'row', alignItems: 'center', paddingVertical: hp(1.5), paddingHorizontal: wp(3), backgroundColor: '#F2F2F7', borderRadius: 12, marginRight: wp(3) },
  radioSelected: { backgroundColor: '#E5F1FF', borderWidth: 1, borderColor: '#007AFF' },
  radioCircle: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: '#999', alignItems: 'center', justifyContent: 'center', marginRight: wp(3) },
  radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#007AFF' },
  radioLabel: { fontSize: hp(1.8), color: '#666' },
  radioLabelSelected: { color: '#007AFF', fontWeight: '500' },
  checkboxGroup: { flexDirection: 'row', flexWrap: 'wrap', gap: wp(3), marginTop: hp(1) },
  checkbox: { flexDirection: 'row', alignItems: 'center', paddingVertical: hp(1), paddingHorizontal: wp(3), backgroundColor: '#F2F2F7', borderRadius: 12 },
  checkboxSelected: { backgroundColor: '#E5F1FF', borderWidth: 1, borderColor: '#007AFF' },
  checkboxBox: { width: 20, height: 20, borderRadius: 4, borderWidth: 2, borderColor: '#999', alignItems: 'center', justifyContent: 'center', marginRight: wp(3) },
  checkboxCheck: { width: 10, height: 10, backgroundColor: '#007AFF' },
  checkboxLabel: { fontSize: hp(1.8), color: '#666' },
  checkboxLabelSelected: { color: '#007AFF', fontWeight: '500' },
  textInput: { backgroundColor: '#F2F2F7', borderRadius: 12, paddingHorizontal: wp(4), paddingVertical: hp(1.8), fontSize: hp(1.8) },
  sliderContainer: { gap: hp(3) },
  sliderRow: { flexDirection: 'row', justifyContent: 'space-between' },
  sliderLabel: { fontSize: hp(1.9), color: '#333' },
  sliderValue: { fontSize: hp(1.9), fontWeight: '600', color: '#007AFF' },
  fab: {
    position: 'absolute',
    right: wp(6),
    bottom: hp(4),
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 7,
  },
});

export default styles;
